name: CI

on:
  push:
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Lint
        run: ruff check .

      - name: Test
        run: pytest -q
